apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-front
spec:
  selector:
    matchLabels:
      app: front
  replicas: #{replicas}#
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: #{image-name}#
        ports:
        - containerPort: 4200
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "frontend-hpa"
  labels:
    app: front
spec:
  scaleTargetRef:
    kind: Deployment
    name: deployment-front
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
---
apiVersion: v1
kind: Service
metadata:
  name: service-front
spec:
  selector:
    app: front
  ports:
  - protocol: "TCP"
    port: 4200
    targetPort: 4200
  type: LoadBalancer