name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - main
      - feature/*
  paths:
    include:
      - backend/*
variables: 
- group: 'var-back'
stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool:
      name: Default
      demands: java
    steps:
    - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
      displayName: 'Prepare analysis on SonarCloud'
      inputs:
        SonarCloud: SonarCloud
        organization: miguewn06
        scannerMode: CLI
        configMode: manual
        cliProjectKey: 'miguewn06_MyProject_back'
        cliProjectName: miguewn06_MyProject_back
        cliSources: backend
        extraProperties: |
          sonar.exclusions= node_modules/**, acceptanceTest/**, performanceTest/**, .dockerfile, .gitignore, Dockerfile
          sonar.sources= .
          sonar.sourceEncoding= UTF-8
          sonar.language= js
          sonar.javascript.file.suffixes=.js
    - task: SonarSource.sonarcloud.ce096e50-6155-4de8-8800-4221aaeed4a1.SonarCloudAnalyze@1
      displayName: 'Run Code Analysis'
      continueOnError: true
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens in app.js'
      inputs:
        rootDirectory: backend
        targetFiles: app.js
    - task: Docker@1
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
      displayName: build
      inputs:
        command: build
        dockerFile: backend/Dockerfile
        imageName: 'registry.digitalocean.com/reto-devops/back:$(Build.BuildId)'
    - script: dockle --exit-code 1 --exit-level fatal registry.digitalocean.com/reto-devops/back:$(Build.BuildId)
      displayName: DockleSecurityLintern
    - task: Docker@1
      condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
      displayName: push
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DigitalOcean-DockerRegistry'
        command: push
        imageName: 'registry.digitalocean.com/reto-devops/back:$(Build.BuildId)'
- stage: Deploy_DEV
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - job: DeployJob
    pool:
      name: Default
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens in **/*.yaml'
      inputs:
        rootDirectory: backend
        targetFiles: '*.yaml'
    - task: Kubernetes@1
      displayName: 'kubectl apply'
      inputs:
        kubernetesServiceEndpoint: 'DigitalOcean-k8s'
        command: apply
        arguments: '-f $(System.DefaultWorkingDirectory)/backend/deployment-back.yaml -n dev'
- stage: Tests
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  jobs:
  - job: AcceptanceTest
    pool:
      name: Default
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens'
      inputs:
        targetFiles: '$(System.DefaultWorkingDirectory)/backend/acceptanceTest/testcases/**'  
    - script: sleep 30
    - script: vrest-ng-cli run --projectdir=$(System.DefaultWorkingDirectory)/backend/acceptanceTest --logger=xunit
      displayName: 'AcceptanceTest_vRestNG'
  - job: PerformanceTest
    dependsOn: AcceptanceTest
    pool:
      name: Default
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens in $(System.DefaultWorkingDirectory)/backend/performanceTest/target.txt'
      inputs:
        targetFiles: '$(System.DefaultWorkingDirectory)/backend/performanceTest/**'
    - script: |
        /devops/vegeta/vegeta attack -targets=$(System.DefaultWorkingDirectory)/backend/performanceTest/target.txt -insecure -rate=5 -duration=30s -timeout 10s -output=results.bin
   
        /devops/vegeta/vegeta report -type=json results.bin > metrics.json
   
        node $(System.DefaultWorkingDirectory)/backend/performanceTest/validate_results.js $(percentage-success-req)
      displayName: 'PerformanceTest_Vegeta'
- stage: Deploy_PDN
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  variables:
    - group: back-var-pdn
  jobs:
  - job: Approval
    pool: server
    steps:
    - task: ManualValidation@0
      displayName: 'Manual Validation'
      inputs:
        notifyUsers: 'matfreire06@gmail.com'
  - job: BuildJob
    pool:
      name: Default
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens in app.js'
      inputs:
        rootDirectory: backend
        targetFiles: app.js
    - task: Docker@1
      displayName: build
      inputs:
        command: build
        dockerFile: backend/Dockerfile
        imageName: 'registry.digitalocean.com/reto-devops/back-pdn:$(Build.BuildId)'
    - script: dockle --exit-code 1 --exit-level fatal registry.digitalocean.com/reto-devops/back-pdn:$(Build.BuildId)
      displayName: DockleSecurityLintern
    - task: Docker@1
      displayName: push
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'DigitalOcean-DockerRegistry'
        command: push
        imageName: 'registry.digitalocean.com/reto-devops/back-pdn:$(Build.BuildId)'
  - job: DeployJob
    dependsOn: BuildJob
    pool:
      name: Default
    steps:
    - task: qetza.replacetokens.replacetokens-task.replacetokens@4
      displayName: 'Replace tokens in **/*.yaml'
      inputs:
        rootDirectory: backend
        targetFiles: '*.yaml'
    - task: Kubernetes@1
      displayName: 'kubectl apply'
      inputs:
        kubernetesServiceEndpoint: 'DigitalOcean-k8s'
        command: apply
        arguments: '-f $(System.DefaultWorkingDirectory)/backend/deployment-back.yaml -n pdn'
- stage: SmokeTest
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
  variables:
    - group: back-var-pdn
  jobs:
  - job: BuildJob
    pool:
      name: Default
    steps:
    - task: oneluckidevWebSmokeTest@1
      inputs:
        url: '$(back-url)'
        expectedReturnCode: '200'
        retryAttemptCount: '3'
        strictSSL: true
        retryDelay: '1000'