apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-back
spec:
  selector:
    matchLabels:
      app: back
  replicas: #{replicas}#
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: back
        image: #{image-name}#
        ports:
        - containerPort: 3000
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "backend-hpa"
  labels:
    app: back
spec:
  scaleTargetRef:
    kind: Deployment
    name: deployment-back
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90
---
apiVersion: v1
kind: Service
metadata:
  name: service-back
spec:
  selector:
    app: back
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer